// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// filterRouteChoices_cpp
List filterRouteChoices_cpp(List neighbours, NumericVector currentVs, NumericVector lastVs, List retracedVs, NumericVector V_outside_aoi);
RcppExport SEXP _visitorFlowTool_filterRouteChoices_cpp(SEXP neighboursSEXP, SEXP currentVsSEXP, SEXP lastVsSEXP, SEXP retracedVsSEXP, SEXP V_outside_aoiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type neighbours(neighboursSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lastVs(lastVsSEXP);
    Rcpp::traits::input_parameter< List >::type retracedVs(retracedVsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V_outside_aoi(V_outside_aoiSEXP);
    rcpp_result_gen = Rcpp::wrap(filterRouteChoices_cpp(neighbours, currentVs, lastVs, retracedVs, V_outside_aoi));
    return rcpp_result_gen;
END_RCPP
}
// chooseBestRoutes_cpp
List chooseBestRoutes_cpp(List viableRoutes, DataFrame DULN_df, List priorVs, StringVector agentTyps, DataFrame V_coords_df, NumericVector currentVs, SEXP nodeRow_ptr);
RcppExport SEXP _visitorFlowTool_chooseBestRoutes_cpp(SEXP viableRoutesSEXP, SEXP DULN_dfSEXP, SEXP priorVsSEXP, SEXP agentTypsSEXP, SEXP V_coords_dfSEXP, SEXP currentVsSEXP, SEXP nodeRow_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type viableRoutes(viableRoutesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type DULN_df(DULN_dfSEXP);
    Rcpp::traits::input_parameter< List >::type priorVs(priorVsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type agentTyps(agentTypsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type V_coords_df(V_coords_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nodeRow_ptr(nodeRow_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(chooseBestRoutes_cpp(viableRoutes, DULN_df, priorVs, agentTyps, V_coords_df, currentVs, nodeRow_ptr));
    return rcpp_result_gen;
END_RCPP
}
// buildEdgeMap_cpp
SEXP buildEdgeMap_cpp(DataFrame edgeTable);
RcppExport SEXP _visitorFlowTool_buildEdgeMap_cpp(SEXP edgeTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    rcpp_result_gen = Rcpp::wrap(buildEdgeMap_cpp(edgeTable));
    return rcpp_result_gen;
END_RCPP
}
// buildNodeRowMap_cpp
SEXP buildNodeRowMap_cpp(NumericVector nodeIDs);
RcppExport SEXP _visitorFlowTool_buildNodeRowMap_cpp(SEXP nodeIDsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type nodeIDs(nodeIDsSEXP);
    rcpp_result_gen = Rcpp::wrap(buildNodeRowMap_cpp(nodeIDs));
    return rcpp_result_gen;
END_RCPP
}
// adjListsToPtr_cpp
SEXP adjListsToPtr_cpp(List listOfPointers);
RcppExport SEXP _visitorFlowTool_adjListsToPtr_cpp(SEXP listOfPointersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type listOfPointers(listOfPointersSEXP);
    rcpp_result_gen = Rcpp::wrap(adjListsToPtr_cpp(listOfPointers));
    return rcpp_result_gen;
END_RCPP
}
// getEdges_cpp
List getEdges_cpp(IntegerVector currentVs, IntegerVector nextVs, SEXP edgeMap_ptr, bool usingPathToGoal, List pathToGoal, List oldPriorEs);
RcppExport SEXP _visitorFlowTool_getEdges_cpp(SEXP currentVsSEXP, SEXP nextVsSEXP, SEXP edgeMap_ptrSEXP, SEXP usingPathToGoalSEXP, SEXP pathToGoalSEXP, SEXP oldPriorEsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nextVs(nextVsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type edgeMap_ptr(edgeMap_ptrSEXP);
    Rcpp::traits::input_parameter< bool >::type usingPathToGoal(usingPathToGoalSEXP);
    Rcpp::traits::input_parameter< List >::type pathToGoal(pathToGoalSEXP);
    Rcpp::traits::input_parameter< List >::type oldPriorEs(oldPriorEsSEXP);
    rcpp_result_gen = Rcpp::wrap(getEdges_cpp(currentVs, nextVs, edgeMap_ptr, usingPathToGoal, pathToGoal, oldPriorEs));
    return rcpp_result_gen;
END_RCPP
}
// getVisitedEdges_cpp
IntegerVector getVisitedEdges_cpp(IntegerVector nextVs, IntegerVector lastPriorVs, DataFrame edgeTable);
RcppExport SEXP _visitorFlowTool_getVisitedEdges_cpp(SEXP nextVsSEXP, SEXP lastPriorVsSEXP, SEXP edgeTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type nextVs(nextVsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lastPriorVs(lastPriorVsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    rcpp_result_gen = Rcpp::wrap(getVisitedEdges_cpp(nextVs, lastPriorVs, edgeTable));
    return rcpp_result_gen;
END_RCPP
}
// updateNicestHistory_cpp
List updateNicestHistory_cpp(List nicestPriorVs, std::vector<int> nicestCurrentVs);
RcppExport SEXP _visitorFlowTool_updateNicestHistory_cpp(SEXP nicestPriorVsSEXP, SEXP nicestCurrentVsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nicestPriorVs(nicestPriorVsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type nicestCurrentVs(nicestCurrentVsSEXP);
    rcpp_result_gen = Rcpp::wrap(updateNicestHistory_cpp(nicestPriorVs, nicestCurrentVs));
    return rcpp_result_gen;
END_RCPP
}
// retraceSteps_cpp
List retraceSteps_cpp(std::vector<int> currentVs, std::vector<int> nextVs, List priorVs, List retracedVs);
RcppExport SEXP _visitorFlowTool_retraceSteps_cpp(SEXP currentVsSEXP, SEXP nextVsSEXP, SEXP priorVsSEXP, SEXP retracedVsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type nextVs(nextVsSEXP);
    Rcpp::traits::input_parameter< List >::type priorVs(priorVsSEXP);
    Rcpp::traits::input_parameter< List >::type retracedVs(retracedVsSEXP);
    rcpp_result_gen = Rcpp::wrap(retraceSteps_cpp(currentVs, nextVs, priorVs, retracedVs));
    return rcpp_result_gen;
END_RCPP
}
// historyToPassage_cpp
List historyToPassage_cpp(DataFrame agentTable, DataFrame edgeTable, DataFrame vertexTable);
RcppExport SEXP _visitorFlowTool_historyToPassage_cpp(SEXP agentTableSEXP, SEXP edgeTableSEXP, SEXP vertexTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type agentTable(agentTableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type vertexTable(vertexTableSEXP);
    rcpp_result_gen = Rcpp::wrap(historyToPassage_cpp(agentTable, edgeTable, vertexTable));
    return rcpp_result_gen;
END_RCPP
}
// appendCurrentToPrior_cpp
List appendCurrentToPrior_cpp(List priorVs, List pathToGoal, IntegerVector currentVs, StringVector behaviour);
RcppExport SEXP _visitorFlowTool_appendCurrentToPrior_cpp(SEXP priorVsSEXP, SEXP pathToGoalSEXP, SEXP currentVsSEXP, SEXP behaviourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type priorVs(priorVsSEXP);
    Rcpp::traits::input_parameter< List >::type pathToGoal(pathToGoalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type behaviour(behaviourSEXP);
    rcpp_result_gen = Rcpp::wrap(appendCurrentToPrior_cpp(priorVs, pathToGoal, currentVs, behaviour));
    return rcpp_result_gen;
END_RCPP
}
// generateAdjListAndDistTbl_cpp
List generateAdjListAndDistTbl_cpp(DataFrame edgeTable, DataFrame vertexTable);
RcppExport SEXP _visitorFlowTool_generateAdjListAndDistTbl_cpp(SEXP edgeTableSEXP, SEXP vertexTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type vertexTable(vertexTableSEXP);
    rcpp_result_gen = Rcpp::wrap(generateAdjListAndDistTbl_cpp(edgeTable, vertexTable));
    return rcpp_result_gen;
END_RCPP
}
// findShortestRoute_cpp
List findShortestRoute_cpp(SEXP adj_ptr, String weighingMethod, std::vector<int> src_v, std::vector<int> goal_v, std::vector<std::string> agentTyps);
RcppExport SEXP _visitorFlowTool_findShortestRoute_cpp(SEXP adj_ptrSEXP, SEXP weighingMethodSEXP, SEXP src_vSEXP, SEXP goal_vSEXP, SEXP agentTypsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type adj_ptr(adj_ptrSEXP);
    Rcpp::traits::input_parameter< String >::type weighingMethod(weighingMethodSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type src_v(src_vSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type goal_v(goal_vSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type agentTyps(agentTypsSEXP);
    rcpp_result_gen = Rcpp::wrap(findShortestRoute_cpp(adj_ptr, weighingMethod, src_v, goal_v, agentTyps));
    return rcpp_result_gen;
END_RCPP
}
// findClosestAOI_cpp
List findClosestAOI_cpp(std::vector<std::string> AOIList_o, std::vector<std::string> AOI_v, SEXP adj_ptr, std::vector<int> src_v, std::vector<double> agentSpeeds, std::vector<double> agentDurations, std::vector<std::string> AOI_aois, std::vector<double> AOI_dulns, std::vector<std::string> agentTyps, std::vector<double> AOI_areas);
RcppExport SEXP _visitorFlowTool_findClosestAOI_cpp(SEXP AOIList_oSEXP, SEXP AOI_vSEXP, SEXP adj_ptrSEXP, SEXP src_vSEXP, SEXP agentSpeedsSEXP, SEXP agentDurationsSEXP, SEXP AOI_aoisSEXP, SEXP AOI_dulnsSEXP, SEXP agentTypsSEXP, SEXP AOI_areasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type AOIList_o(AOIList_oSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type AOI_v(AOI_vSEXP);
    Rcpp::traits::input_parameter< SEXP >::type adj_ptr(adj_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type src_v(src_vSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type agentSpeeds(agentSpeedsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type agentDurations(agentDurationsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type AOI_aois(AOI_aoisSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type AOI_dulns(AOI_dulnsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type agentTyps(agentTypsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type AOI_areas(AOI_areasSEXP);
    rcpp_result_gen = Rcpp::wrap(findClosestAOI_cpp(AOIList_o, AOI_v, adj_ptr, src_v, agentSpeeds, agentDurations, AOI_aois, AOI_dulns, agentTyps, AOI_areas));
    return rcpp_result_gen;
END_RCPP
}
// ccl_big_patches
IntegerVector ccl_big_patches(IntegerVector src, int nrow, int ncol, double min_cells);
RcppExport SEXP _visitorFlowTool_ccl_big_patches(SEXP srcSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP min_cellsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type src(srcSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< double >::type min_cells(min_cellsSEXP);
    rcpp_result_gen = Rcpp::wrap(ccl_big_patches(src, nrow, ncol, min_cells));
    return rcpp_result_gen;
END_RCPP
}
// svf_horizon
NumericVector svf_horizon(NumericVector H, int nrow, int ncol, double res, int n_dir, double max_dist_m);
RcppExport SEXP _visitorFlowTool_svf_horizon(SEXP HSEXP, SEXP nrowSEXP, SEXP ncolSEXP, SEXP resSEXP, SEXP n_dirSEXP, SEXP max_dist_mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type H(HSEXP);
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type ncol(ncolSEXP);
    Rcpp::traits::input_parameter< double >::type res(resSEXP);
    Rcpp::traits::input_parameter< int >::type n_dir(n_dirSEXP);
    Rcpp::traits::input_parameter< double >::type max_dist_m(max_dist_mSEXP);
    rcpp_result_gen = Rcpp::wrap(svf_horizon(H, nrow, ncol, res, n_dir, max_dist_m));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_visitorFlowTool_filterRouteChoices_cpp", (DL_FUNC) &_visitorFlowTool_filterRouteChoices_cpp, 5},
    {"_visitorFlowTool_chooseBestRoutes_cpp", (DL_FUNC) &_visitorFlowTool_chooseBestRoutes_cpp, 7},
    {"_visitorFlowTool_buildEdgeMap_cpp", (DL_FUNC) &_visitorFlowTool_buildEdgeMap_cpp, 1},
    {"_visitorFlowTool_buildNodeRowMap_cpp", (DL_FUNC) &_visitorFlowTool_buildNodeRowMap_cpp, 1},
    {"_visitorFlowTool_adjListsToPtr_cpp", (DL_FUNC) &_visitorFlowTool_adjListsToPtr_cpp, 1},
    {"_visitorFlowTool_getEdges_cpp", (DL_FUNC) &_visitorFlowTool_getEdges_cpp, 6},
    {"_visitorFlowTool_getVisitedEdges_cpp", (DL_FUNC) &_visitorFlowTool_getVisitedEdges_cpp, 3},
    {"_visitorFlowTool_updateNicestHistory_cpp", (DL_FUNC) &_visitorFlowTool_updateNicestHistory_cpp, 2},
    {"_visitorFlowTool_retraceSteps_cpp", (DL_FUNC) &_visitorFlowTool_retraceSteps_cpp, 4},
    {"_visitorFlowTool_historyToPassage_cpp", (DL_FUNC) &_visitorFlowTool_historyToPassage_cpp, 3},
    {"_visitorFlowTool_appendCurrentToPrior_cpp", (DL_FUNC) &_visitorFlowTool_appendCurrentToPrior_cpp, 4},
    {"_visitorFlowTool_generateAdjListAndDistTbl_cpp", (DL_FUNC) &_visitorFlowTool_generateAdjListAndDistTbl_cpp, 2},
    {"_visitorFlowTool_findShortestRoute_cpp", (DL_FUNC) &_visitorFlowTool_findShortestRoute_cpp, 5},
    {"_visitorFlowTool_findClosestAOI_cpp", (DL_FUNC) &_visitorFlowTool_findClosestAOI_cpp, 10},
    {"_visitorFlowTool_ccl_big_patches", (DL_FUNC) &_visitorFlowTool_ccl_big_patches, 4},
    {"_visitorFlowTool_svf_horizon", (DL_FUNC) &_visitorFlowTool_svf_horizon, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_visitorFlowTool(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
