// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// filterRouteChoices_cpp
List filterRouteChoices_cpp(List neighbours, NumericVector currentVs, NumericVector lastVs, List retracedVs, NumericVector V_outside_aoi);
RcppExport SEXP _visitorFlowTool_filterRouteChoices_cpp(SEXP neighboursSEXP, SEXP currentVsSEXP, SEXP lastVsSEXP, SEXP retracedVsSEXP, SEXP V_outside_aoiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type neighbours(neighboursSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lastVs(lastVsSEXP);
    Rcpp::traits::input_parameter< List >::type retracedVs(retracedVsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type V_outside_aoi(V_outside_aoiSEXP);
    rcpp_result_gen = Rcpp::wrap(filterRouteChoices_cpp(neighbours, currentVs, lastVs, retracedVs, V_outside_aoi));
    return rcpp_result_gen;
END_RCPP
}
// chooseBestRoutes_cpp
List chooseBestRoutes_cpp(List viableRoutes, DataFrame DULN_df, List priorVs, StringVector agentTyps, DataFrame V_coords_df, NumericVector currentVs);
RcppExport SEXP _visitorFlowTool_chooseBestRoutes_cpp(SEXP viableRoutesSEXP, SEXP DULN_dfSEXP, SEXP priorVsSEXP, SEXP agentTypsSEXP, SEXP V_coords_dfSEXP, SEXP currentVsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type viableRoutes(viableRoutesSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type DULN_df(DULN_dfSEXP);
    Rcpp::traits::input_parameter< List >::type priorVs(priorVsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type agentTyps(agentTypsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type V_coords_df(V_coords_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type currentVs(currentVsSEXP);
    rcpp_result_gen = Rcpp::wrap(chooseBestRoutes_cpp(viableRoutes, DULN_df, priorVs, agentTyps, V_coords_df, currentVs));
    return rcpp_result_gen;
END_RCPP
}
// getEdges_cpp
List getEdges_cpp(IntegerVector currentVs, IntegerVector nextVs, DataFrame edgeTable, bool usingPathToGoal, List pathToGoal, List oldPriorEs);
RcppExport SEXP _visitorFlowTool_getEdges_cpp(SEXP currentVsSEXP, SEXP nextVsSEXP, SEXP edgeTableSEXP, SEXP usingPathToGoalSEXP, SEXP pathToGoalSEXP, SEXP oldPriorEsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nextVs(nextVsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    Rcpp::traits::input_parameter< bool >::type usingPathToGoal(usingPathToGoalSEXP);
    Rcpp::traits::input_parameter< List >::type pathToGoal(pathToGoalSEXP);
    Rcpp::traits::input_parameter< List >::type oldPriorEs(oldPriorEsSEXP);
    rcpp_result_gen = Rcpp::wrap(getEdges_cpp(currentVs, nextVs, edgeTable, usingPathToGoal, pathToGoal, oldPriorEs));
    return rcpp_result_gen;
END_RCPP
}
// getVisitedEdges_cpp
IntegerVector getVisitedEdges_cpp(IntegerVector nextVs, IntegerVector lastPriorVs, DataFrame edgeTable);
RcppExport SEXP _visitorFlowTool_getVisitedEdges_cpp(SEXP nextVsSEXP, SEXP lastPriorVsSEXP, SEXP edgeTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type nextVs(nextVsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lastPriorVs(lastPriorVsSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    rcpp_result_gen = Rcpp::wrap(getVisitedEdges_cpp(nextVs, lastPriorVs, edgeTable));
    return rcpp_result_gen;
END_RCPP
}
// updateNicestHistory_cpp
List updateNicestHistory_cpp(List nicestPriorVs, std::vector<int> nicestCurrentVs);
RcppExport SEXP _visitorFlowTool_updateNicestHistory_cpp(SEXP nicestPriorVsSEXP, SEXP nicestCurrentVsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nicestPriorVs(nicestPriorVsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type nicestCurrentVs(nicestCurrentVsSEXP);
    rcpp_result_gen = Rcpp::wrap(updateNicestHistory_cpp(nicestPriorVs, nicestCurrentVs));
    return rcpp_result_gen;
END_RCPP
}
// retraceSteps_cpp
List retraceSteps_cpp(std::vector<int> currentVs, std::vector<int> nextVs, List priorVs, List retracedVs);
RcppExport SEXP _visitorFlowTool_retraceSteps_cpp(SEXP currentVsSEXP, SEXP nextVsSEXP, SEXP priorVsSEXP, SEXP retracedVsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<int> >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type nextVs(nextVsSEXP);
    Rcpp::traits::input_parameter< List >::type priorVs(priorVsSEXP);
    Rcpp::traits::input_parameter< List >::type retracedVs(retracedVsSEXP);
    rcpp_result_gen = Rcpp::wrap(retraceSteps_cpp(currentVs, nextVs, priorVs, retracedVs));
    return rcpp_result_gen;
END_RCPP
}
// historyToPassage_cpp
List historyToPassage_cpp(DataFrame agentTable, DataFrame edgeTable, DataFrame vertexTable);
RcppExport SEXP _visitorFlowTool_historyToPassage_cpp(SEXP agentTableSEXP, SEXP edgeTableSEXP, SEXP vertexTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type agentTable(agentTableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type vertexTable(vertexTableSEXP);
    rcpp_result_gen = Rcpp::wrap(historyToPassage_cpp(agentTable, edgeTable, vertexTable));
    return rcpp_result_gen;
END_RCPP
}
// appendCurrentToPrior_cpp
List appendCurrentToPrior_cpp(List priorVs, List pathToGoal, IntegerVector currentVs, StringVector behaviour);
RcppExport SEXP _visitorFlowTool_appendCurrentToPrior_cpp(SEXP priorVsSEXP, SEXP pathToGoalSEXP, SEXP currentVsSEXP, SEXP behaviourSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type priorVs(priorVsSEXP);
    Rcpp::traits::input_parameter< List >::type pathToGoal(pathToGoalSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type currentVs(currentVsSEXP);
    Rcpp::traits::input_parameter< StringVector >::type behaviour(behaviourSEXP);
    rcpp_result_gen = Rcpp::wrap(appendCurrentToPrior_cpp(priorVs, pathToGoal, currentVs, behaviour));
    return rcpp_result_gen;
END_RCPP
}
// generateAdjListAndDistTbl_cpp
List generateAdjListAndDistTbl_cpp(DataFrame edgeTable, DataFrame vertexTable);
RcppExport SEXP _visitorFlowTool_generateAdjListAndDistTbl_cpp(SEXP edgeTableSEXP, SEXP vertexTableSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type edgeTable(edgeTableSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type vertexTable(vertexTableSEXP);
    rcpp_result_gen = Rcpp::wrap(generateAdjListAndDistTbl_cpp(edgeTable, vertexTable));
    return rcpp_result_gen;
END_RCPP
}
// findShortestRoute_cpp
List findShortestRoute_cpp(int V_ptr, std::vector<std::vector<int>> adjList_IDs_ptr, std::vector<std::vector<double>> adjList_dist_ptr_walkNat, std::vector<std::vector<double>> adjList_dist_ptr_walkNat_attr, std::vector<std::vector<double>> adjList_dist_ptr_walkNat_ATTR, std::vector<std::vector<double>> adjList_dist_ptr_walkSoc, std::vector<std::vector<double>> adjList_dist_ptr_walkSoc_attr, std::vector<std::vector<double>> adjList_dist_ptr_walkSoc_ATTR, std::vector<std::vector<double>> adjList_dist_ptr_dogNat, std::vector<std::vector<double>> adjList_dist_ptr_dogNat_attr, std::vector<std::vector<double>> adjList_dist_ptr_dogNat_ATTR, std::vector<std::vector<double>> adjList_dist_ptr_dogProx, std::vector<std::vector<double>> adjList_dist_ptr_dogProx_attr, std::vector<std::vector<double>> adjList_dist_ptr_dogProx_ATTR, std::vector<std::vector<double>> adjList_dist_ptr_ebikeNat, std::vector<std::vector<double>> adjList_dist_ptr_ebikeNat_attr, std::vector<std::vector<double>> adjList_dist_ptr_ebikeNat_ATTR, std::vector<std::vector<double>> adjList_dist_ptr_bikeSport, std::vector<std::vector<double>> adjList_dist_ptr_bikeSport_attr, std::vector<std::vector<double>> adjList_dist_ptr_bikeSport_ATTR, std::vector<std::vector<double>> adjList_dist_ptr_jogger, std::vector<std::vector<double>> adjList_dist_ptr_jogger_attr, std::vector<std::vector<double>> adjList_dist_ptr_jogger_ATTR, String weighingMethod, std::vector<int> src_v, std::vector<int> goal_v, std::vector<std::string> agentTyps);
RcppExport SEXP _visitorFlowTool_findShortestRoute_cpp(SEXP V_ptrSEXP, SEXP adjList_IDs_ptrSEXP, SEXP adjList_dist_ptr_walkNatSEXP, SEXP adjList_dist_ptr_walkNat_attrSEXP, SEXP adjList_dist_ptr_walkNat_ATTRSEXP, SEXP adjList_dist_ptr_walkSocSEXP, SEXP adjList_dist_ptr_walkSoc_attrSEXP, SEXP adjList_dist_ptr_walkSoc_ATTRSEXP, SEXP adjList_dist_ptr_dogNatSEXP, SEXP adjList_dist_ptr_dogNat_attrSEXP, SEXP adjList_dist_ptr_dogNat_ATTRSEXP, SEXP adjList_dist_ptr_dogProxSEXP, SEXP adjList_dist_ptr_dogProx_attrSEXP, SEXP adjList_dist_ptr_dogProx_ATTRSEXP, SEXP adjList_dist_ptr_ebikeNatSEXP, SEXP adjList_dist_ptr_ebikeNat_attrSEXP, SEXP adjList_dist_ptr_ebikeNat_ATTRSEXP, SEXP adjList_dist_ptr_bikeSportSEXP, SEXP adjList_dist_ptr_bikeSport_attrSEXP, SEXP adjList_dist_ptr_bikeSport_ATTRSEXP, SEXP adjList_dist_ptr_joggerSEXP, SEXP adjList_dist_ptr_jogger_attrSEXP, SEXP adjList_dist_ptr_jogger_ATTRSEXP, SEXP weighingMethodSEXP, SEXP src_vSEXP, SEXP goal_vSEXP, SEXP agentTypsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type V_ptr(V_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int>> >::type adjList_IDs_ptr(adjList_IDs_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkNat(adjList_dist_ptr_walkNatSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkNat_attr(adjList_dist_ptr_walkNat_attrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkNat_ATTR(adjList_dist_ptr_walkNat_ATTRSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkSoc(adjList_dist_ptr_walkSocSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkSoc_attr(adjList_dist_ptr_walkSoc_attrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkSoc_ATTR(adjList_dist_ptr_walkSoc_ATTRSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogNat(adjList_dist_ptr_dogNatSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogNat_attr(adjList_dist_ptr_dogNat_attrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogNat_ATTR(adjList_dist_ptr_dogNat_ATTRSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogProx(adjList_dist_ptr_dogProxSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogProx_attr(adjList_dist_ptr_dogProx_attrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogProx_ATTR(adjList_dist_ptr_dogProx_ATTRSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_ebikeNat(adjList_dist_ptr_ebikeNatSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_ebikeNat_attr(adjList_dist_ptr_ebikeNat_attrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_ebikeNat_ATTR(adjList_dist_ptr_ebikeNat_ATTRSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_bikeSport(adjList_dist_ptr_bikeSportSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_bikeSport_attr(adjList_dist_ptr_bikeSport_attrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_bikeSport_ATTR(adjList_dist_ptr_bikeSport_ATTRSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_jogger(adjList_dist_ptr_joggerSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_jogger_attr(adjList_dist_ptr_jogger_attrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_jogger_ATTR(adjList_dist_ptr_jogger_ATTRSEXP);
    Rcpp::traits::input_parameter< String >::type weighingMethod(weighingMethodSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type src_v(src_vSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type goal_v(goal_vSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type agentTyps(agentTypsSEXP);
    rcpp_result_gen = Rcpp::wrap(findShortestRoute_cpp(V_ptr, adjList_IDs_ptr, adjList_dist_ptr_walkNat, adjList_dist_ptr_walkNat_attr, adjList_dist_ptr_walkNat_ATTR, adjList_dist_ptr_walkSoc, adjList_dist_ptr_walkSoc_attr, adjList_dist_ptr_walkSoc_ATTR, adjList_dist_ptr_dogNat, adjList_dist_ptr_dogNat_attr, adjList_dist_ptr_dogNat_ATTR, adjList_dist_ptr_dogProx, adjList_dist_ptr_dogProx_attr, adjList_dist_ptr_dogProx_ATTR, adjList_dist_ptr_ebikeNat, adjList_dist_ptr_ebikeNat_attr, adjList_dist_ptr_ebikeNat_ATTR, adjList_dist_ptr_bikeSport, adjList_dist_ptr_bikeSport_attr, adjList_dist_ptr_bikeSport_ATTR, adjList_dist_ptr_jogger, adjList_dist_ptr_jogger_attr, adjList_dist_ptr_jogger_ATTR, weighingMethod, src_v, goal_v, agentTyps));
    return rcpp_result_gen;
END_RCPP
}
// findClosestAOI_cpp
List findClosestAOI_cpp(std::vector<std::string> AOIList_o, std::vector<std::string> AOI_v, int V_ptr, std::vector<std::vector<int>> adjList_IDs_ptr, std::vector<std::vector<double>> adjList_dist_ptr_walkNat, std::vector<std::vector<double>> adjList_dist_ptr_walkSoc, std::vector<std::vector<double>> adjList_dist_ptr_dogNat, std::vector<std::vector<double>> adjList_dist_ptr_dogProx, std::vector<std::vector<double>> adjList_dist_ptr_ebikeNat, std::vector<std::vector<double>> adjList_dist_ptr_bikeSport, std::vector<std::vector<double>> adjList_dist_ptr_jogger, std::vector<int> src_v, std::vector<double> agentSpeeds, std::vector<double> agentDurations, std::vector<std::string> AOI_aois, std::vector<double> AOI_dulns, std::vector<std::string> agentTyps, std::vector<double> AOI_areas);
RcppExport SEXP _visitorFlowTool_findClosestAOI_cpp(SEXP AOIList_oSEXP, SEXP AOI_vSEXP, SEXP V_ptrSEXP, SEXP adjList_IDs_ptrSEXP, SEXP adjList_dist_ptr_walkNatSEXP, SEXP adjList_dist_ptr_walkSocSEXP, SEXP adjList_dist_ptr_dogNatSEXP, SEXP adjList_dist_ptr_dogProxSEXP, SEXP adjList_dist_ptr_ebikeNatSEXP, SEXP adjList_dist_ptr_bikeSportSEXP, SEXP adjList_dist_ptr_joggerSEXP, SEXP src_vSEXP, SEXP agentSpeedsSEXP, SEXP agentDurationsSEXP, SEXP AOI_aoisSEXP, SEXP AOI_dulnsSEXP, SEXP agentTypsSEXP, SEXP AOI_areasSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type AOIList_o(AOIList_oSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type AOI_v(AOI_vSEXP);
    Rcpp::traits::input_parameter< int >::type V_ptr(V_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<int>> >::type adjList_IDs_ptr(adjList_IDs_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkNat(adjList_dist_ptr_walkNatSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_walkSoc(adjList_dist_ptr_walkSocSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogNat(adjList_dist_ptr_dogNatSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_dogProx(adjList_dist_ptr_dogProxSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_ebikeNat(adjList_dist_ptr_ebikeNatSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_bikeSport(adjList_dist_ptr_bikeSportSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<double>> >::type adjList_dist_ptr_jogger(adjList_dist_ptr_joggerSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type src_v(src_vSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type agentSpeeds(agentSpeedsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type agentDurations(agentDurationsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type AOI_aois(AOI_aoisSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type AOI_dulns(AOI_dulnsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type agentTyps(agentTypsSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type AOI_areas(AOI_areasSEXP);
    rcpp_result_gen = Rcpp::wrap(findClosestAOI_cpp(AOIList_o, AOI_v, V_ptr, adjList_IDs_ptr, adjList_dist_ptr_walkNat, adjList_dist_ptr_walkSoc, adjList_dist_ptr_dogNat, adjList_dist_ptr_dogProx, adjList_dist_ptr_ebikeNat, adjList_dist_ptr_bikeSport, adjList_dist_ptr_jogger, src_v, agentSpeeds, agentDurations, AOI_aois, AOI_dulns, agentTyps, AOI_areas));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_visitorFlowTool_filterRouteChoices_cpp", (DL_FUNC) &_visitorFlowTool_filterRouteChoices_cpp, 5},
    {"_visitorFlowTool_chooseBestRoutes_cpp", (DL_FUNC) &_visitorFlowTool_chooseBestRoutes_cpp, 6},
    {"_visitorFlowTool_getEdges_cpp", (DL_FUNC) &_visitorFlowTool_getEdges_cpp, 6},
    {"_visitorFlowTool_getVisitedEdges_cpp", (DL_FUNC) &_visitorFlowTool_getVisitedEdges_cpp, 3},
    {"_visitorFlowTool_updateNicestHistory_cpp", (DL_FUNC) &_visitorFlowTool_updateNicestHistory_cpp, 2},
    {"_visitorFlowTool_retraceSteps_cpp", (DL_FUNC) &_visitorFlowTool_retraceSteps_cpp, 4},
    {"_visitorFlowTool_historyToPassage_cpp", (DL_FUNC) &_visitorFlowTool_historyToPassage_cpp, 3},
    {"_visitorFlowTool_appendCurrentToPrior_cpp", (DL_FUNC) &_visitorFlowTool_appendCurrentToPrior_cpp, 4},
    {"_visitorFlowTool_generateAdjListAndDistTbl_cpp", (DL_FUNC) &_visitorFlowTool_generateAdjListAndDistTbl_cpp, 2},
    {"_visitorFlowTool_findShortestRoute_cpp", (DL_FUNC) &_visitorFlowTool_findShortestRoute_cpp, 27},
    {"_visitorFlowTool_findClosestAOI_cpp", (DL_FUNC) &_visitorFlowTool_findClosestAOI_cpp, 18},
    {NULL, NULL, 0}
};

RcppExport void R_init_visitorFlowTool(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
